In [1]:
import pandas as pd

In [2]:
res = pd.read_csv("./outputs/experiments_results.csv")

In [3]:
res

,selector,experiment,model,r2,rmse,adj_r2,rse,best_params
0,logsum,baseline,LinearRegression,-8539.175821,169.361925,-11475.269959,196.356196,NaN
1,logsum,baseline,Lasso,0.298373,1.535095,0.057156,1.779771,NaN
2,logsum,baseline,RandomForest,0.254498,1.582365,-0.001804,1.834575,NaN
3,logsum,baseline,LightGBM,0.287555,1.546885,0.042617,1.793441,NaN
4,logsum,optuna,Lasso,0.299019,1.534389,0.058024,1.778952,{'alpha': 0.001964215267886893}
5,logsum,optuna,RandomForest,0.289808,1.544438,0.045645,1.790603,"{'n_estimators': 279, 'max_depth': 16, 'min_sa..."
6,logsum,optuna,LightGBM,0.299448,1.533919,0.058600,1.778407,"{'num_leaves': 26, 'learning_rate': 0.02616196..."
7,shap,baseline,LinearRegression,0.276599,1.558734,0.274532,1.561182,NaN
8,shap,baseline,Lasso,0.273274,1.562312,0.271198,1.564765,NaN
9,shap,baseline,RandomForest,0.230078,1.608072,0.227879,1.610597,NaN
10,shap,baseline,LightGBM,0.274745,1.560729,0.272673,1.563180,NaN
11,shap,optuna,Lasso,0.276682,1.558644,0.274616,1.561091,{'alpha': 0.00011659114744959731}
12,shap,optuna,RandomForest,0.275717,1.559684,0.273648,1.562133,"{'n_estimators': 257, 'max_depth': 17, 'min_sa..."
13,shap,optuna,LightGBM,0.285871,1.548712,0.283830,1.551144,"{'num_leaves': 53, 'learning_rate': 0.12713545..."

In [6]:
new_rows = pd.DataFrame([
    {"selector": "no_selection", "experiment": "baseline", "model" : "LinerRegression", "r2": 0.037778, "rmse": 1.797711, "adj_r2": -0.388162, "rse": 2.159555, "best_params": None},
    {"selector": "no_selection", "experiment": "baseline", "model" : "Lasso", "r2": 0.298314, "rmse": 1.535160, "adj_r2": -0.012296, "rse": 1.844158, "best_params": None},
    {"selector": "no_selection", "experiment": "baseline", "model" : "RandomForest", "r2": 0.261876, "rmse": 1.574516, "adj_r2": -0.064864, "rse": 1.891435, "best_params": None},
    {"selector": "no_selection", "experiment": "baseline", "model" : "LightGBM", "r2": 0.282033, "rmse": 1.552868, "adj_r2": -0.035785, "rse": 1.865430, "best_params": None}
])

In [7]:
df = pd.concat([res,new_rows], ignore_index=True)

In [8]:
df

,selector,experiment,model,r2,rmse,adj_r2,rse,best_params
0,logsum,baseline,LinearRegression,-8539.175821,169.361925,-11475.269959,196.356196,NaN
1,logsum,baseline,Lasso,0.298373,1.535095,0.057156,1.779771,NaN
2,logsum,baseline,RandomForest,0.254498,1.582365,-0.001804,1.834575,NaN
3,logsum,baseline,LightGBM,0.287555,1.546885,0.042617,1.793441,NaN
4,logsum,optuna,Lasso,0.299019,1.534389,0.058024,1.778952,{'alpha': 0.001964215267886893}
5,logsum,optuna,RandomForest,0.289808,1.544438,0.045645,1.790603,"{'n_estimators': 279, 'max_depth': 16, 'min_sa..."
6,logsum,optuna,LightGBM,0.299448,1.533919,0.058600,1.778407,"{'num_leaves': 26, 'learning_rate': 0.02616196..."
7,shap,baseline,LinearRegression,0.276599,1.558734,0.274532,1.561182,NaN
8,shap,baseline,Lasso,0.273274,1.562312,0.271198,1.564765,NaN
9,shap,baseline,RandomForest,0.230078,1.608072,0.227879,1.610597,NaN
10,shap,baseline,LightGBM,0.274745,1.560729,0.272673,1.563180,NaN
11,shap,optuna,Lasso,0.276682,1.558644,0.274616,1.561091,{'alpha': 0.00011659114744959731}
12,shap,optuna,RandomForest,0.275717,1.559684,0.273648,1.562133,"{'n_estimators': 257, 'max_depth': 17, 'min_sa..."
13,shap,optuna,LightGBM,0.285871,1.548712,0.283830,1.551144,"{'num_leaves': 53, 'learning_rate': 0.12713545..."
14,no_selection,baseline,LinerRegression,0.037778,1.797711,-0.388162,2.159555,None
15,no_selection,baseline,Lasso,0.298314,1.535160,-0.012296,1.844158,None
16,no_selection,baseline,RandomForest,0.261876,1.574516,-0.064864,1.891435,None
17,no_selection,baseline,LightGBM,0.282033,1.552868,-0.035785,1.865430,None